---
title: "Testing"
output: html_document
---

Data analysis is only useful if it's correct, and if it's not, it [can do considerable harm](https://theconversation.com/the-reinhart-rogoff-error-or-how-not-to-excel-at-economics-13646).
While no amount of testing can ever conclusively prove that there aren't mistakes in code, a few simple practices can reassure us that it's probably all right.
This tutorial will introduce some of the tools R gives you for checking your code and show you how to integrate them into your workflow.

> FIXME:
>
> Draw diagram of feedback loops in testing.
>
> Clarify the three major tools within testing described here (assertions in functions, expectations and unit tests, and testing data integrity).
> This might help a reader apply these lessons to their own problem:
> they want to write a function, so they'll use assertions, or they will write tests first for test driven development.
> Clarify the tools up front, so the lessons are more applicable and easier to fit them together.

## Testing Basics

Start here to learn what testing can and can't do, and how to think about building useful tests.

## Writing Unit Tests

Unit testing is how experienced developers check their code as they build it and re-check it as they modify it. This tutorial will show you how to create and run unit tests using the testthat library.

## Test-Driven Development

Writing tests before you write code helps you figure out what that code should do, and helps you tell when you're done. This tutorial will introduce the basic ideas of test-driven development.

## Handling Errors

You can't always prevent errors, but in R, you can always catch them and do something about them. This tutorial will show you how to handle errors yourself.

## Testing in Production

It doesn't matter how careful you were when writing your code if someone then feeds it data that doesn't make sense. This tutorial will show you how to inspect the data flowing through your pipeline so that you can sleep easily at night.

## Mocking

Some parts of your program will be more difficult to reach for testing than others.  This tutorial introduces a technique called mocking that lets you temporarily replace those bits with simplified or more predictable versions.